import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { api } from '@appdeploy/client';
import './index.css';
import './auth.css';

const money=(n:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(n||0));
const token=()=>localStorage.getItem('crave_token')||'';
const headers=()=>token()?{Authorization:`Bearer ${token()}`} as any:{};
const go=(hash:string)=>{location.hash=hash;window.scrollTo(0,0)};
const errorText=(e:any)=>e?.response?.data?.error||e?.response?.data?.message||e?.message||'Something went wrong. Please try again.';

function PasswordField({value,onChange,autoComplete,placeholder='Password (8+ characters)'}:{value:string;onChange:(v:string)=>void;autoComplete:string;placeholder?:string}){
 const [show,setShow]=useState(false);
 return <div className="password-wrap"><input type={show?'text':'password'} value={value} onChange={e=>onChange(e.target.value)} autoComplete={autoComplete} placeholder={placeholder} minLength={8} required/><button type="button" className="password-toggle" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(v=>!v)}>{show?'🙈':'👁'}</button></div>;
}
function Shell({user,children,onSignOut}:{user:any;children:any;onSignOut:()=>void}){return <><header><button className="brand text-button" onClick={()=>go('#home')}><span className="mark">⌂</span><span><b>CRAVE HOUSE</b><small>WHATEVER YOU’RE CRAVING.</small></span></button><nav><button className="text-button" onClick={()=>go('#menu')}>Menu</button><button className="text-button" onClick={()=>go('#about')}>About</button>{user?<><button className="text-button" onClick={()=>go('#orders')}>My orders</button><button className="text-button" onClick={()=>go('#account')}>Account</button><button className="text-button" onClick={onSignOut}>Sign out</button></>:<><button className="text-button" onClick={()=>go('#signin')}>Sign in</button><button className="primary" onClick={()=>go('#register')}>Create account</button></>}<button className="cart" onClick={()=>go('#checkout')}>Cart</button></nav></header>{children}</>}

function AuthPage({mode,onSuccess}:{mode:'signin'|'register';onSuccess:(u:any)=>void}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[name,setName]=useState(''),[code,setCode]=useState('');
 const [step,setStep]=useState<'credentials'|'verify'>('credentials'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[cooldown,setCooldown]=useState(0);
 useEffect(()=>{if(!cooldown)return;const t=setInterval(()=>setCooldown(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t)},[cooldown]);
 async function submit(e:any){e.preventDefault();setError('');setNotice('');setBusy(true);try{
  const normalized=email.trim().toLowerCase();
  if(step==='verify'){const r=await api.post(mode==='register'?'/api/auth/verify-signup':'/api/auth/verify-code',{email:normalized,token:code,full_name:name});if(r.data?.access_token){localStorage.setItem('crave_token',r.data.access_token);if(r.data.refresh_token)localStorage.setItem('crave_refresh_token',r.data.refresh_token);onSuccess(r.data.user);return}setError(r.data?.error||'Verification failed. Request a new code.');return;}
  if(mode==='register'){if(!name.trim()){setError('Please enter your full name.');return}if(password!==confirm){setError('Passwords do not match.');return}const r=await api.post('/api/auth/signup',{email:normalized,password,full_name:name.trim()});if(r.data?.verification_required){setStep('verify');setCooldown(60);setNotice('We sent a 6-digit verification code to your email.');return}if(r.data?.access_token){localStorage.setItem('crave_token',r.data.access_token);onSuccess(r.data.user);return}setError(r.data?.error||'Could not start registration.');return;}
  const r=await api.post('/api/auth/signin',{email:normalized,password});if(r.data?.access_token){localStorage.setItem('crave_token',r.data.access_token);if(r.data.refresh_token)localStorage.setItem('crave_refresh_token',r.data.refresh_token);onSuccess(r.data.user)}else setError(r.data?.error||'Sign in failed.');
 }catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function resend(){if(cooldown)return;setError('');try{const r=await api.post('/api/auth/resend',{email:email.trim().toLowerCase()});if(r.data?.ok){setCooldown(60);setNotice('A new verification code has been sent.')}else setError(r.data?.error||'Could not resend the verification email.')}catch(e){setError(errorText(e))}}
 return <main className="auth-page"><form className="auth-card" onSubmit={submit}><button type="button" className="text-button" onClick={()=>go('#home')}>← Back to Crave House</button><span className="eyebrow">CRAVE HOUSE</span>{step==='credentials'?<><h1>{mode==='signin'?'Welcome back':'Create your account'}</h1><p>{mode==='signin'?'Sign in to manage your orders and favourites.':'Verify your email before your Crave House account is activated.'}</p>{mode==='register'&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/>}<input type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/><PasswordField value={password} onChange={setPassword} autoComplete={mode==='register'?'new-password':'current-password'}/>{mode==='register'&&<><PasswordField value={confirm} onChange={setConfirm} autoComplete="new-password" placeholder="Confirm password"/><p className="field-help">Use at least 8 characters. Both passwords must match.</p></>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='signin'?'Sign in':'Send verification code'}</button>{mode==='signin'&&<button type="button" className="text-button" onClick={async()=>{setError('');try{const r=await api.post('/api/auth/code',{email:email.trim().toLowerCase()});if(r.data?.ok){setStep('verify');setCooldown(60);setNotice('Check your email for the 6-digit sign-in code.')}else setError(r.data?.error||'Could not send the sign-in code.')}catch(e){setError(errorText(e))}}}>Sign in with email code</button>}</>:<><h1>Verify your email</h1><p>Enter the 6-digit code sent to <b>{email}</b>.</p><input autoFocus inputMode="numeric" autoComplete="one-time-code" maxLength={6} pattern="[0-9]{6}" placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} required/><button className="primary" disabled={busy||code.length!==6}>{busy?'Verifying…':'Verify and continue'}</button><button type="button" className="text-button" disabled={cooldown>0} onClick={resend}>{cooldown?`Resend in ${cooldown}s`:'Resend code'}</button><button type="button" className="text-button" onClick={()=>{setStep('credentials');setCode('');setError('')}}>Use a different email</button></>}{error&&<p className="error">{error}</p>}{notice&&<p className="notice">{notice}</p>}<div className="auth-switch">{mode==='signin'?<>New to Crave House? <button type="button" className="text-button" onClick={()=>go('#register')}>Create an account</button></>:<>Already registered? <button type="button" className="text-button" onClick={()=>go('#signin')}>Sign in</button></>}</div></form></main>;
}
function Home(){return <main className="page hero"><div><span className="eyebrow">KUBWA • ABUJA</span><h1>Good food.<br/>Big cravings.</h1><p>Meals, quick bites, snacks, sweets and drinks — made for whatever you’re craving.</p><button className="primary" onClick={()=>go('#menu')}>Order now</button></div><div className="hero-art"><b>CRAVE</b><strong>HOUSE</strong><small>RESTAURANT & QUICK SERVICE</small></div></main>}
function About(){return <main className="page"><span className="eyebrow">ABOUT CRAVE HOUSE</span><h1>Whatever you’re craving.</h1><p>Crave House is a modern quick-service restaurant concept built around Nigerian meals, quick bites, snacks, sweets and drinks, with dine-in, takeaway and delivery.</p><section className="panel"><h2>Built for real restaurant operations</h2><p>The platform connects customers, kitchen operations and the owner’s admin workspace through one reliable ordering system.</p><div className="row"><span>Location</span><b>Kubwa, Abuja</b></div><div className="row"><span>Service</span><b>Dine in · Takeaway · Delivery</b></div></section></main>}
function Menu({products,categories,setCart}:{products:any[];categories:any[];setCart:any}){const [cat,setCat]=useState('all'),[search,setSearch]=useState('');const shown=products.filter(p=>(cat==='all'||p.category_id===cat)&&(!search||`${p.name} ${p.description||''}`.toLowerCase().includes(search.toLowerCase())));return <main className="page"><div className="section-head"><div><span className="eyebrow">THE CRAVE MENU</span><h1>Pick your craving.</h1></div><input placeholder="Search food, snacks, drinks…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="chips"><button className={cat==='all'?'active':''} onClick={()=>setCat('all')}>All</button>{categories.map(c=><button className={cat===c.id?'active':''} key={c.id} onClick={()=>setCat(c.id)}>{c.name}</button>)}</div><div className="grid">{shown.map(p=><article className="card" key={p.id}><div className="photo">{p.image_url?<img src={p.image_url} alt={p.name}/>:<span>🍽️</span>}</div><div className="body"><h3>{p.name}</h3><p>{p.description||'Freshly prepared at Crave House.'}</p><div className="price"><b>{money(p.price)}</b><button onClick={()=>setCart((c:any[])=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]})}>+ Add</button></div></div></article>)}</div>{!shown.length&&<div className="panel"><p>No matching items are available right now.</p></div>}</main>}
function Checkout({user,cart,setCart}:{user:any;cart:any[];setCart:any}){const [type,setType]=useState('delivery'),[phone,setPhone]=useState(''),[address,setAddress]=useState(''),[message,setMessage]=useState('');const total=cart.reduce((s,p)=>s+Number(p.price)*p.qty,0);async function place(){if(!user){go('#signin');return}if(!cart.length){setMessage('Your cart is empty.');return}try{const r=await api.post('/api/orders',{order_type:type,payment_method:'cash_on_delivery',customer_name:user.user_metadata?.full_name||user.email,customer_phone:phone,notes:address,items:cart.map(p=>({product_id:p.id,quantity:p.qty}))});if(r.data?.order_number){setCart([]);setMessage(`Order ${r.data.order_number} is now pending.`);setTimeout(()=>go('#orders'),700)}else setMessage(r.data?.error||'Could not create your order.')}catch(e){setMessage(errorText(e))}}return <main className="page narrow"><span className="eyebrow">CHECKOUT</span><h1>Your order.</h1>{cart.map(p=><div className="row" key={p.id}><span>{p.qty} × {p.name}</span><b>{money(p.price*p.qty)}</b></div>)}<div className="total"><b>Total</b><strong>{money(total)}</strong></div><div className="chips"><button className={type==='delivery'?'active':''} onClick={()=>setType('delivery')}>Delivery</button><button className={type==='takeaway'?'active':''} onClick={()=>setType('takeaway')}>Takeaway</button><button className={type==='dine_in'?'active':''} onClick={()=>setType('dine_in')}>Dine in</button></div><input placeholder="Phone number" value={phone} onChange={e=>setPhone(e.target.value)}/>{type==='delivery'&&<textarea placeholder="Delivery address" value={address} onChange={e=>setAddress(e.target.value)}/>}<button className="primary" onClick={place}>Place order</button>{message&&<p className="notice">{message}</p>}</main>}
function Orders(){const [orders,setOrders]=useState<any[]>([]);useEffect(()=>{api.get('/api/orders').then(r=>setOrders(r.data||[])).catch(()=>setOrders([]))},[]);return <main className="page"><span className="eyebrow">MY ORDERS</span><h1>Order history.</h1>{orders.length?orders.map(o=><article className="panel" key={o.id}><div className="row"><b>{o.order_number}</b><strong>{money(o.total)}</strong></div><p className="status">{String(o.status).replaceAll('_',' ')}</p>{o.order_items?.map((i:any)=><div className="row" key={i.id}><span>{i.quantity} × {i.product_name}</span><span>{money(i.line_total)}</span></div>)}</article>):<div className="panel"><p>No orders yet. Your future cravings will appear here.</p><button className="primary" onClick={()=>go('#menu')}>Browse menu</button></div>}</main>}
function Account({user,onSignOut}:{user:any;onSignOut:()=>void}){return <main className="page narrow"><span className="eyebrow">MY ACCOUNT</span><h1>Your account.</h1><section className="panel"><div className="row"><span>Name</span><b>{user?.user_metadata?.full_name||'Customer'}</b></div><div className="row"><span>Email</span><b>{user?.email}</b></div><button className="primary" onClick={onSignOut}>Sign out</button></section></main>}
function App(){const [route,setRoute]=useState(location.hash||'#home'),[user,setUser]=useState<any>(null),[products,setProducts]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[cart,setCart]=useState<any[]>([]);useEffect(()=>{const h=()=>setRoute(location.hash||'#home');addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);useEffect(()=>{api.get('/api/products').then(r=>setProducts(r.data||[])).catch(()=>{});api.get('/api/categories').then(r=>setCategories(r.data||[])).catch(()=>{})},[]);useEffect(()=>{const hash=location.hash.replace(/^#/,'');const params=new URLSearchParams(hash);const access=params.get('access_token');const refresh=params.get('refresh_token');if(access){localStorage.setItem('crave_token',access);if(refresh)localStorage.setItem('crave_refresh_token',refresh);history.replaceState(null,'',location.pathname+location.search+'#home');setRoute('#home')}else if(params.get('error')){localStorage.removeItem('crave_token');localStorage.removeItem('crave_refresh_token');history.replaceState(null,'',location.pathname+location.search+'#signin');setRoute('#signin')}const current=localStorage.getItem('crave_token');if(!current)return;api.get('/api/auth/me').then(r=>setUser(r.data?.user||null)).catch(()=>{localStorage.removeItem('crave_token');localStorage.removeItem('crave_refresh_token')})},[]);const signOut=()=>{localStorage.removeItem('crave_token');localStorage.removeItem('crave_refresh_token');setUser(null);go('#home')};const success=(u:any)=>{setUser(u);go('#home')};let content:any;if(route==='#signin')content=<AuthPage mode="signin" onSuccess={success}/>;else if(route==='#register')content=<AuthPage mode="register" onSuccess={success}/>;else if(route==='#about')content=<About/>;else if(route==='#menu')content=<Menu products={products} categories={categories} setCart={setCart}/>;else if(route==='#checkout')content=<Checkout user={user} cart={cart} setCart={setCart}/>;else if(route==='#orders')content=user?<Orders/>:<AuthPage mode="signin" onSuccess={success}/>;else if(route==='#account')content=user?<Account user={user} onSignOut={signOut}/>:<AuthPage mode="signin" onSuccess={success}/>;else content=<Home/>;return <Shell user={user} onSignOut={signOut}>{content}<footer><b>CRAVE HOUSE</b><span>Whatever You’re Craving.</span></footer></Shell>}

createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
